import type { DiaPlano, Nivel, TipoOracao } from "./types";

export const INTERPRETE =
  "O que este texto significava para os primeiros leitores? O que ele ensina sobre Deus, sobre o pecado e sobre a graça em Cristo?";

export const ORACOES: Record<TipoOracao, { nome: string; passos: string[] }> = {
  adoracao: {
    nome: "Adoração",
    passos: [
      "Reconheça quem Deus é: sua santidade, poder e amor.",
      "Use palavras do texto de hoje para louvá-lo.",
      "Termine em silêncio por um minuto, apenas contemplando a Deus.",
    ],
  },
  confissao: {
    nome: "Confissão",
    passos: [
      "Peça ao Espírito Santo que mostre o que precisa ser trazido à luz.",
      "Nomeie o pecado a Deus, sem desculpas nem comparações.",
      "Descanse na promessa de perdão em Cristo e agradeça por ela.",
    ],
  },
  gratidao: {
    nome: "Gratidão",
    passos: [
      "Lembre três coisas pelas quais você é grato(a) hoje.",
      "Agradeça a Deus pelo que o texto de hoje revelou dele.",
      "Agradeça por uma pessoa específica que Deus colocou em sua vida.",
    ],
  },
  suplica: {
    nome: "Súplica",
    passos: [
      "Apresente a Deus, com clareza, aquilo de que você precisa.",
      "Peça também o que o texto de hoje o(a) encoraja a pedir.",
      "Entregue o resultado a Deus e confie na sabedoria dele.",
    ],
  },
  intercessao: {
    nome: "Intercessão",
    passos: [
      "Diga em voz alta o nome de cada pessoa por quem vai orar.",
      "Peça a Deus o bem espiritual dessas pessoas, e não só o alívio de seus problemas.",
      "Escolha uma delas para ligar ou escrever ainda esta semana.",
    ],
  },
};

const iniciando: DiaPlano[] = [
  {
    dia: 1,
    titulo: "Quem é Jesus",
    referencia: "João 1:1-18",
    observe: "O que este texto diz sobre quem Jesus é e o que Ele faz?",
    aplique: "Se Jesus é a luz e a vida, o que isso muda no meu dia de hoje?",
    oracao: { tipo: "adoracao", foco: "Louve a Deus por enviar o seu Filho para viver entre nós." },
    desafio: "Escreva em uma frase quem Jesus é para você hoje.",
  },
  {
    dia: 2,
    titulo: "Nascer de novo",
    referencia: "João 3:1-21",
    observe: "O que Jesus explica a Nicodemos sobre nascer de novo e sobre o amor de Deus?",
    aplique: "Onde eu ainda confio mais em mim do que em Jesus?",
    oracao: { tipo: "confissao", foco: "Traga a Deus as áreas em que você tenta se justificar por conta própria." },
    desafio: "Releia João 3:16 em voz alta, devagar, e escolha memorizá-lo esta semana.",
  },
  {
    dia: 3,
    titulo: "A água que sacia",
    referencia: "João 4:1-26",
    observe: "O que Jesus sabe sobre a mulher e como Ele a trata?",
    aplique: "Que sede só Jesus pode saciar em mim?",
    oracao: { tipo: "gratidao", foco: "Agradeça pelas pessoas que Deus usou para apontar você a Cristo." },
    desafio: "Mande uma mensagem de agradecimento a alguém que o(a) ajudou na fé.",
  },
  {
    dia: 4,
    titulo: "O pão da vida",
    referencia: "João 6:35-40",
    observe: "Que promessas Jesus faz a quem vem a Ele?",
    aplique: "O que significa, na prática, vir a Jesus hoje com o que eu tenho?",
    oracao: { tipo: "suplica", foco: "Apresente a Deus uma necessidade concreta e anote a data do pedido." },
    desafio: "Anote um pedido de oração específico para acompanhar nas próximas semanas.",
  },
  {
    dia: 5,
    titulo: "O bom pastor",
    referencia: "João 10:1-18",
    observe: "Que ações o bom pastor pratica pelas ovelhas neste texto?",
    aplique: "Em que área da vida eu preciso ouvir a voz do Pastor?",
    oracao: { tipo: "adoracao", foco: "Adore a Cristo por dar a vida pelas ovelhas." },
    desafio: "Fique 10 minutos em silêncio, sem celular, diante de Deus.",
  },
  {
    dia: 6,
    titulo: "O caminho ao Pai",
    referencia: "João 14:1-14",
    observe: "O que Jesus promete aos discípulos aflitos e o que diz sobre si mesmo?",
    aplique: "Que inquietação posso entregar a Cristo hoje?",
    oracao: { tipo: "intercessao", foco: "Ore por alguém que está aflito neste momento." },
    desafio: "Envie uma palavra de ânimo a uma pessoa que passa por dificuldade.",
  },
  {
    dia: 7,
    titulo: "Permanecer em Cristo",
    referencia: "João 15:1-11",
    observe: "O que significa permanecer em Jesus e o que acontece com quem permanece?",
    aplique: "O que hoje me afasta de permanecer em Cristo?",
    oracao: { tipo: "gratidao", foco: "Agradeça a Deus por tudo o que Ele tem feito em você nesta semana." },
    desafio:
      "Combine com alguém da igreja de irem juntos ao próximo culto. Se ainda não tem igreja, peça a um amigo crente que o(a) convide.",
  },
];

const crescendo: DiaPlano[] = [
  {
    dia: 1,
    titulo: "O caminho do justo",
    referencia: "Salmos 1",
    observe: "Que contrastes o salmista faz entre o justo e o ímpio?",
    aplique: "Que hábito me aproxima da Palavra e qual me afasta?",
    oracao: { tipo: "adoracao", foco: "Louve a Deus pela sua Palavra, que é alimento e direção." },
    desafio: "Escolha um horário fixo para ler a Bíblia amanhã e coloque um alarme.",
  },
  {
    dia: 2,
    titulo: "Um coração quebrantado",
    referencia: "Salmos 51",
    observe: "O que Davi pede a Deus e em que ele confia para ser perdoado?",
    aplique: "Há algo que preciso confessar a Deus hoje, sem desculpas?",
    oracao: { tipo: "confissao", foco: "Use as palavras do Salmo 51 para confessar seus pecados e pedir um coração limpo." },
    desafio: "Se houver alguém a quem você deve um pedido de perdão, dê o primeiro passo hoje.",
  },
  {
    dia: 3,
    titulo: "As bem-aventuranças",
    referencia: "Mateus 5:1-16",
    observe: "Que tipo de pessoa Jesus chama de bem-aventurada?",
    aplique: "Qual dessas bem-aventuranças mais desafia o meu jeito de viver?",
    oracao: { tipo: "suplica", foco: "Peça a Deus que forme em você o caráter que Jesus descreve." },
    desafio: "Faça uma boa ação em segredo, sem que ninguém saiba.",
  },
  {
    dia: 4,
    titulo: "Aprendendo a orar",
    referencia: "Mateus 6:5-15",
    observe: "Como Jesus ensina a orar e o que Ele critica na oração dos hipócritas?",
    aplique: "Que parte do Pai-Nosso eu costumo esquecer nas minhas orações?",
    oracao: { tipo: "adoracao", foco: "Ore o Pai-Nosso frase por frase, parando para desenvolver cada pedido com suas palavras." },
    desafio: "Ore em um lugar reservado, sem pressa e sem distrações, por 10 minutos.",
  },
  {
    dia: 5,
    titulo: "Paz com Deus",
    referencia: "Romanos 5:1-11",
    observe: "Que bênçãos recebemos por sermos justificados pela fé?",
    aplique: "O que mudaria em mim se eu vivesse mais convencido(a) de que tenho paz com Deus?",
    oracao: { tipo: "gratidao", foco: "Agradeça a Cristo por ter morrido por nós quando ainda éramos fracos." },
    desafio: "Escreva três motivos concretos de gratidão a Deus por Cristo.",
  },
  {
    dia: 6,
    titulo: "Nenhuma condenação",
    referencia: "Romanos 8:1-17",
    observe: "O que o texto diz sobre a condenação, o Espírito e a adoção como filhos?",
    aplique: "Onde ainda vivo como escravo do medo em vez de filho(a) amado(a)?",
    oracao: { tipo: "adoracao", foco: "Chame Deus de Pai e agradeça pelo Espírito que testifica que somos seus filhos." },
    desafio: "Compartilhe com um irmão da fé uma luta sua e peça oração.",
  },
  {
    dia: 7,
    titulo: "Alegria e confiança",
    referencia: "Filipenses 4:4-13",
    observe: "O que Paulo manda fazer com a ansiedade e o que promete em troca?",
    aplique: "Qual ansiedade posso entregar a Deus em oração agora?",
    oracao: { tipo: "suplica", foco: "Transforme cada preocupação em um pedido a Deus, com ações de graças." },
    desafio: "Escreva suas preocupações em um papel, ore por cada uma e guarde o papel na Bíblia.",
  },
];

const firmando: DiaPlano[] = [
  {
    dia: 1,
    titulo: "Justificados pela fé",
    referencia: "Romanos 3:21-31",
    observe: "Como o texto explica que o pecador é justificado diante de Deus?",
    aplique: "Onde ainda tento acrescentar méritos meus à obra de Cristo?",
    oracao: { tipo: "adoracao", foco: "Adore a Deus por ser justo e, ao mesmo tempo, justificador de quem crê em Jesus." },
    desafio: "Explique em duas frases, para si mesmo(a), o que é justificação pela fé.",
  },
  {
    dia: 2,
    titulo: "Escolhidos em Cristo",
    referencia: "Efésios 1:3-14",
    observe: "Que bênçãos espirituais Paulo lista e o que faz cada Pessoa da Trindade?",
    aplique: "O que significa para mim ter sido escolhido(a) em Cristo antes da fundação do mundo?",
    oracao: { tipo: "adoracao", foco: "Bendiga a Deus, Pai, Filho e Espírito Santo, pelas bênçãos que recebeu em Cristo." },
    desafio: "Escreva uma carta curta de gratidão a Deus pela salvação.",
  },
  {
    dia: 3,
    titulo: "Salvos pela graça",
    referencia: "Efésios 2:1-10",
    observe: "Como Paulo descreve o nosso estado antes de Cristo e o que Deus fez?",
    aplique: "Como a graça, e não as obras, deve moldar a minha maneira de servir?",
    oracao: { tipo: "gratidao", foco: "Agradeça pela graça que o salvou e o criou para boas obras." },
    desafio: "Identifique uma boa obra que Deus preparou para você esta semana e faça-a.",
  },
  {
    dia: 4,
    titulo: "Vida nova em Cristo",
    referencia: "Colossenses 3:1-17",
    observe: "O que devemos abandonar e o que devemos vestir como novo povo de Deus?",
    aplique: "Qual hábito antigo preciso despir e qual virtude preciso vestir?",
    oracao: { tipo: "confissao", foco: "Confesse o que precisa fazer morrer e peça poder para viver a nova vida." },
    desafio: "Pratique hoje uma virtude do texto (compaixão, paciência ou perdão) com alguém específico.",
  },
  {
    dia: 5,
    titulo: "Fé que produz obras",
    referencia: "Tiago 2:14-26",
    observe: "Que relação Tiago estabelece entre fé e obras e que exemplos ele usa?",
    aplique: "Que obras mostram que a minha fé é viva?",
    oracao: { tipo: "suplica", foco: "Peça a Deus uma fé que se expresse em amor concreto." },
    desafio: "Ajude alguém necessitado de forma prática esta semana.",
  },
  {
    dia: 6,
    titulo: "Esperança viva",
    referencia: "1 Pedro 1:3-12",
    observe: "Que razões para esperança e alegria Pedro apresenta a cristãos que sofrem?",
    aplique: "Como essa esperança viva pode me sustentar numa dificuldade atual?",
    oracao: { tipo: "intercessao", foco: "Ore por irmãos que sofrem por causa da fé ou de dificuldades." },
    desafio: "Ligue para um irmão que passa por provação e ore com ele.",
  },
  {
    dia: 7,
    titulo: "A disciplina do Pai",
    referencia: "Hebreus 12:1-13",
    observe: "O que o autor diz sobre a corrida da fé e sobre a disciplina do Senhor?",
    aplique: "Como posso enxergar uma dificuldade atual à luz do cuidado do Pai?",
    oracao: { tipo: "suplica", foco: "Peça perseverança e um coração que aceite a correção do Pai." },
    desafio: "Conte a um irmão maduro na fé uma dificuldade sua e peça conselho.",
  },
];

const multiplicando: DiaPlano[] = [
  {
    dia: 1,
    titulo: "Ide e fazei discípulos",
    referencia: "Mateus 28:16-20",
    observe: "Qual é a autoridade de Cristo, o mandamento e a promessa nesta comissão?",
    aplique: "A quem Deus colocou ao meu redor para eu discipular ou evangelizar?",
    oracao: { tipo: "intercessao", foco: "Ore pelo nome de três pessoas que ainda não conhecem a Cristo." },
    desafio: "Convide uma dessas pessoas para um café e ouça a história dela.",
  },
  {
    dia: 2,
    titulo: "Uma igreja em comunhão",
    referencia: "Atos 2:42-47",
    observe: "Que práticas marcavam a vida da primeira igreja?",
    aplique: "Qual dessas práticas eu poderia fortalecer na minha igreja local?",
    oracao: { tipo: "gratidao", foco: "Agradeça a Deus pela sua igreja e por irmãos específicos." },
    desafio: "Convide alguém para uma refeição ou para a comunhão em sua casa.",
  },
  {
    dia: 3,
    titulo: "Levar as cargas uns dos outros",
    referencia: "Gálatas 6:1-10",
    observe: "Como o texto orienta a cuidar de quem caiu e a levar as cargas uns dos outros?",
    aplique: "Quem ao meu redor está carregando um peso que eu poderia ajudar a levar?",
    oracao: { tipo: "intercessao", foco: "Ore por alguém que carrega um fardo pesado." },
    desafio: "Ofereça ajuda concreta a alguém esta semana e faça sem alarde.",
  },
  {
    dia: 4,
    titulo: "Um corpo, muitos membros",
    referencia: "Efésios 4:1-16",
    observe: "Como Paulo descreve a unidade da igreja e o papel dos dons?",
    aplique: "Que dom Deus me deu e como posso usá-lo para edificar o corpo?",
    oracao: { tipo: "suplica", foco: "Peça a Deus humildade e mansidão para preservar a unidade da igreja." },
    desafio: "Converse com seu pastor ou líder sobre onde você pode servir com seus dons.",
  },
  {
    dia: 5,
    titulo: "Confiar a outros o que aprendeu",
    referencia: "2 Timóteo 2:1-13",
    observe: "O que Paulo pede que Timóteo faça com o que aprendeu?",
    aplique: "Em quem estou investindo para que aprenda a ensinar outros também?",
    oracao: { tipo: "suplica", foco: "Peça sabedoria e coragem para ensinar e discipular com fidelidade." },
    desafio: "Marque um encontro regular com alguém mais novo na fé para ler a Bíblia juntos.",
  },
  {
    dia: 6,
    titulo: "Pastorear com humildade",
    referencia: "1 Pedro 5:1-11",
    observe: "Que orientações Pedro dá aos presbíteros e a toda a igreja, e qual é a promessa final?",
    aplique: "Como posso cuidar dos outros com humildade, sem buscar reconhecimento?",
    oracao: { tipo: "intercessao", foco: "Ore pelos pastores, presbíteros e líderes da sua igreja." },
    desafio: "Escreva uma mensagem de encorajamento ao seu pastor.",
  },
  {
    dia: 7,
    titulo: "Um culto vivo",
    referencia: "Romanos 12:1-13",
    observe: "O que Paulo chama de culto racional e como isso aparece nas relações do dia a dia?",
    aplique: "Que área da minha vida ainda não entreguei a Deus como sacrifício vivo?",
    oracao: { tipo: "adoracao", foco: "Ofereça-se a Deus por inteiro e agradeça a misericórdia que motiva a sua entrega." },
    desafio: "Pratique hospitalidade esta semana com alguém que precise.",
  },
];

export const PLANOS: Record<Nivel, DiaPlano[]> = { iniciando, crescendo, firmando, multiplicando };
